# Generated by Django 4.2.7 on 2025-11-22 05:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('altura', models.FloatField(blank=True, help_text='Altura en cm', null=True, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(250.0)])),
                ('peso', models.FloatField(blank=True, help_text='Peso en kg', null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(300.0)])),
                ('condiciones_medicas', models.TextField(blank=True, help_text='Condiciones médicas conocidas (separadas por comas)')),
                ('objetivos', models.CharField(choices=[('peso', 'Pérdida de Peso'), ('musculacion', 'Ganancia de Músculo'), ('mantenimiento', 'Mantenimiento'), ('resistencia', 'Resistencia'), ('flexibilidad', 'Flexibilidad'), ('salud', 'Salud General')], default='salud', help_text='Objetivo principal de entrenamiento', max_length=100)),
                ('nivel_experiencia', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', help_text='Nivel de experiencia en entrenamiento', max_length=20)),
                ('dias_entrenamiento', models.IntegerField(default=3, help_text='Días disponibles para entrenar por semana', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('restricciones', models.TextField(blank=True, help_text='Restricciones físicas o médicas adicionales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la rutina', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la rutina')),
                ('dias_semana', models.IntegerField(help_text='Días de entrenamiento por semana', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], help_text='Nivel de dificultad requerido', max_length=20)),
                ('objetivo', models.CharField(choices=[('peso', 'Pérdida de Peso'), ('musculacion', 'Ganancia de Músculo'), ('mantenimiento', 'Mantenimiento'), ('resistencia', 'Resistencia'), ('flexibilidad', 'Flexibilidad'), ('salud', 'Salud General')], help_text='Objetivo principal de la rutina', max_length=20)),
                ('ejercicios', models.JSONField(help_text='Lista de ejercicios estructurados como JSON')),
                ('duracion', models.CharField(help_text='Duración estimada por sesión (ej: 45 minutos)', max_length=50)),
                ('intensidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], help_text='Nivel de intensidad', max_length=20)),
                ('calorias_estimadas', models.IntegerField(default=0, help_text='Calorías estimadas quemadas por sesión')),
                ('restricciones_medicas', models.TextField(blank=True, help_text='Condiciones médicas que contraindican esta rutina')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso_actual', models.FloatField(help_text='Peso actual en kg', validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(300.0)])),
                ('imc_actual', models.FloatField(help_text='IMC calculado en esta fecha')),
                ('satisfaccion', models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')], default=3, help_text='Nivel de satisfacción con la rutina')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales del usuario')),
                ('rutina_realizada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='recommender.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacion_medica', models.TextField(help_text='Explicación médica de por qué se recomienda esta rutina')),
                ('precauciones', models.TextField(blank=True, help_text='Precauciones específicas para el usuario')),
                ('objetivos_especificos', models.TextField(help_text='Objetivos específicos a alcanzar con esta rutina')),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True, help_text='Indica si la recomendación sigue siendo válida')),
                ('reglas_aplicadas', models.JSONField(default=dict, help_text='Reglas lógicas aplicadas para generar esta recomendación')),
                ('score_confianza', models.FloatField(default=0.0, help_text='Score de confianza de la recomendación (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('rutina_recomendada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='recommender.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendación Médica',
                'verbose_name_plural': 'Recomendaciones Médicas',
                'ordering': ['-fecha_recomendacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imc', models.FloatField(blank=True, help_text='Índice de Masa Corporal calculado', null=True)),
                ('clasificacion_imc', models.CharField(blank=True, help_text='Clasificación del IMC (bajo_peso, normal, sobrepeso, obesidad)', max_length=50)),
                ('presion_arterial', models.CharField(blank=True, help_text='Presión arterial (ej: 120/80)', max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, help_text='Frecuencia cardíaca en reposo (bpm)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(220)])),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas')),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos actuales')),
                ('historial_lesiones', models.TextField(blank=True, help_text='Historial de lesiones previas')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Médico',
                'verbose_name_plural': 'Perfiles Médicos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
