# Generated by Django 4.2.7 on 2025-12-01 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='condiciones_contraindicadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de condiciones de salud que contraindican esta rutina'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='plan_semanal',
            field=models.JSONField(blank=True, default=dict, help_text='Plan semanal de ejercicios estructurado por días'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='condiciones_salud',
            field=models.JSONField(blank=True, default=list, help_text='Lista de condiciones de salud destacadas que restringen rutinas'),
        ),
        migrations.CreateModel(
            name='SeguimientoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del entrenamiento')),
                ('dia_semana', models.CharField(help_text='Día de la semana (Lunes, Martes, etc.)', max_length=20)),
                ('ejercicios_completados', models.JSONField(default=list, help_text='Lista de ejercicios completados en este día')),
                ('ejercicios_totales', models.JSONField(default=list, help_text='Lista de todos los ejercicios programados para este día')),
                ('completado', models.BooleanField(default=False, help_text='Indica si el día completo fue completado')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el entrenamiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_ejercicios', to='recommender.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_ejercicios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Ejercicio',
                'verbose_name_plural': 'Seguimientos de Ejercicios',
                'ordering': ['-fecha', 'dia_semana'],
                'unique_together': {('usuario', 'rutina', 'fecha', 'dia_semana')},
            },
        ),
    ]
